language: rust
notifications:
  webhooks: http://build.servo.org:54856/travis
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows
    - rust: nightly
      name: minimal-versions
      before_script: ~
      script:
        - cargo -Z minimal-versions build --verbose
rust:
  - stable
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections;
        sudo apt-get install ttf-mscorefonts-installer;
    fi
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test
